# Launch instances, runs some tasks
# and then terminate them

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: devopt
    instance_type: t2.medium
    security_group: sg-3efba747 ## default - tudo aberto
    subnet_id: subnet-e61dd881
    image: ami-7abd0209
    region: eu-west-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group_id: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }


- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    always:
      - name: Terminate instances that were previously launched
        ec2:
          state: 'absent'
          instance_ids: "{{ ec2.instance_ids }}"
          region: "eu-west-1"
